---
- name: Install systemd-timesyncd
  ansible.builtin.package:
    name:
      - systemd-timesyncd

- name: Enable systemd-timesyncd at boot
  ansible.builtin.service:
    enabled: true
    name: systemd-timesyncd.service
